### ISSUE TITLE
Figure out how to do a 3D representation of project data with PyVista

### ISSUE THREAD

**Issue by YanickNdepo** [kaufmanno/GSDMA#24]
make a 3D representation of data with striplogs created

**Comment by JorisCoronGSDM** [comment]
1) i've found a solution to display 3D data with Pyvista from : [this website](https://www.hatarilabs.com/ih-en/3d-visualization-of-well-lithology-with-python-pyvista-and-vtk-tutorial).
I still have to:
-comment it
-find the way to display .vtk and .vtu files in the notebook ( as the exemple use ParaView to do it)
-list the mandatory input data for this method

**Comment by JorisCoronGSDM** [comment]
2. I've been able to plot the topo surface.
I still have to figure how to display the .vtu file. I've tried to use meshio as described [here](https://stackoverflow.com/questions/54044958/reading-data-from-a-raw-vtk-vtu-file). It worked to read the file but , i don't already know ho to plot the mesh with this method. I'll also tried the first method from this forum.

**Comment by JorisCoronGSDM** [comment]
3. both plots succed but it's currently not possible to interact with the view. => tried to use ITKwidgets

**Comment by JorisCoronGSDM** [comment]
4. ITKwidgets works to manipulate the plot. (still have to play with parameters to display a better view)
-remaining: list the mandatory imput data format for this method

**Comment by kaufmanno** [comment]
@YanickNdepo , @JorisCoronGSDM There is a link with issue #44 because omfvista lies on top of pyvista

**Comment by JorisCoronGSDM** [comment]
This issue is completed: 
-a [notebook](https://github.com/kaufmanno/GSDMA/blob/omf/playground/3D_visualisation_of_boreholes_with_Pyvista.ipynb) has been created with an example.
-The input data have to be imported from .csv files as you can see it in the example [data](https://github.com/kaufmanno/GSDMA/tree/omf/data/TestData_3DvisPyvi) 
- meshio has to be used to create the mesh
- ITK can be used to interact with the the plot
