### ISSUE TITLE
change the way of integration of lithology and colour in database

### ISSUE THREAD

**Issue by YanickNdepo** [kaufmanno/GSDMA#39]
To avoid 2 records for a level, in a borehole, we must use lithology and colour as fields in the table, not as key, value

**Comment by kaufmanno** [comment]
I would not do this because lithology and colour are just two of all the possible attributes that could be associated to a sample. If you want to add porosity, hydrocarbon content or compressive strength i.e. you would have to add new columns in your table and thus modify the STRUCTURE of your database... If you do not want to limit too much the scope of your development, you would not do that...

**Comment by kaufmanno** [comment]
@YanickNdepo Can we close this issue?

**Comment by YanickNdepo** [comment]
After

**Comment by kaufmanno** [comment]
test this file

![comment](https://user-images.githubusercontent.com/5863078/100470187-121ea700-30d8-11eb-850a-fc5c1df07359.png)
